//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployeeDetail
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CompanyName { get; set; }
        public string Age { get; set; }
        public string Salary { get; set; }
        public string DateOfJoining { get; set; }
        public string MobileNumber { get; set; }
        public string Email { get; set; }
        public string BankName { get; set; }
        public string IFSCCode { get; set; }
        public string AccountNumber { get; set; }
        public string PFNumber { get; set; }
        public string UANNumber { get; set; }
        public string UserPhotoPath { get; set; }
        public string DocumentUploadPath { get; set; }
    }
}
